"""empty message

Revision ID: 8baf6be3f76c
Revises: 4050b9b0a148
Create Date: 2020-01-15 20:38:56.832560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8baf6be3f76c'
down_revision = '4050b9b0a148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('todo_folder_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['todo_folder_id'], ['todo_folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task')
    op.drop_table('list_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_task',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('list_task_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='list_task_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='list_task_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('list_task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('todo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['list_task_id'], ['list_task.id'], name='task_list_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='task_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    op.drop_table('todo')
    op.drop_table('todo_folder')
    # ### end Alembic commands ###
